src/MsCoreOne.FrontMvc/Models/CategoryVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MsCoreOne.FrontMvc.Models
{
    public class CategoryVm
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

src/MsCoreOne.FrontMvc/Models/ErrorViewModel.cs
namespace MsCoreOne.FrontMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/MsCoreOne.FrontMvc/Models/ProductVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MsCoreOne.FrontMvc.Models
{
    public class ProductVm
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public decimal Price { get; set; }

        public string Description { get; set; }

        public int Rating { get; set; }

        public string ThumbnailImageUrl { get; set; }
        
    }
}

src/MsCoreOne.FrontMvc/Components/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MsCoreOne.FrontMvc.Services;
using System.Threading.Tasks;

namespace MsCoreOne.FrontMvc.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        private readonly ICategoryApiClient _categoryApiClient;

        public CategoriesViewComponent(ICategoryApiClient categoryApiClient)
        {
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryApiClient.GetCategories();

            return View(categories);
        }
    }
}

src/MsCoreOne.FrontMvc/Components/StarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MsCoreOne.FrontMvc.Components
{
    public class StarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int rating)
        {
            return View(rating);
        }
    }
}

src/MsCoreOne.FrontMvc/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MsCoreOne.FrontMvc.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult SignIn()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, "oidc");
        }

        public IActionResult SignOut()
        {
            return SignOut(new AuthenticationProperties { RedirectUri = "/" }, "Cookies", "oidc");
        }

        [Authorize]
        public ActionResult MyProfile()
        {
            return View();
        }
    }
}

src/MsCoreOne.FrontMvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MsCoreOne.FrontMvc.Models;
using MsCoreOne.FrontMvc.Services;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MsCoreOne.FrontMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;

        public HomeController(ILogger<HomeController> logger,
            IProductApiClient productApiClient,
            IConfiguration configuration)
        {
            _logger = logger;
            _productApiClient = productApiClient;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index(int? categoryId)
        {
            ViewData["BackendUrl"] = _configuration.GetValue<string>("FrontMvc:BackendUrl");

            var products = Enumerable.Empty<ProductVm>();
            if (categoryId == null)
            {
                _logger.LogInformation("GetProducts called.");
                products = await _productApiClient.GetProducts();
            }
            else
            {
                _logger.LogInformation($"GetProductsByCategoryId called with categoryId: {categoryId.Value}.");
                products = await _productApiClient.GetProductsByCategoryId(categoryId.Value);
            }
            return View(products);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/MsCoreOne.FrontMvc/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MsCoreOne.FrontMvc.Models;
using MsCoreOne.FrontMvc.Services;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MsCoreOne.FrontMvc.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;

        public ProductController(ILogger<ProductController> logger,
            IProductApiClient productApiClient,
            IConfiguration configuration)
        {
            _logger = logger;
            _productApiClient = productApiClient;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index(int productId)
        {
            ViewData["BackendUrl"] = _configuration.GetValue<string>("FrontMvc:BackendUrl");

            var product = await _productApiClient.GetProductById(productId);

            return View(product);
        }
    }
}

src/MsCoreOne.FrontMvc/Views/Home/Index.cshtml
@model IEnumerable<MsCoreOne.FrontMvc.Models.ProductVm>
@{
    ViewData["Title"] = "Home Page";
}
<div class="container">
    <div class="row">
        @if (Model.Any())
        {
            foreach (var product in Model)
            {
                <div class="col-md-4">
                    <figure class="card card-product">
                        <div class="img-wrap"><img height="220" src="@ViewData["BackendUrl"]@product.ThumbnailImageUrl"></div>
                        <figcaption class="info-wrap">
                            <h4 class="title">@product.Name</h4>
                            <p class="desc">@product.Description</p>
                            <div class="rating-wrap">
                                <vc:star rating="@product.Rating"></vc:star>
                            </div>
                        </figcaption>
                        <div class="bottom-wrap">

                            <a asp-controller="Product" asp-action="Index" asp-route-productId="@product.Id" class="btn btn-sm btn-primary float-right">View</a>
                            <a href="" class="btn btn-sm btn-primary float-right mr-2"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
                            <div class="price-wrap h5">
                                <span class="price-new">$@product.Price</span> @*<del class="price-old">$1980</del>*@
                            </div>
                        </div>
                    </figure>
                </div>
            }
        }
        else
        {
            <div class="col">
                <div class="alert alert-secondary" role="alert">
                    No data available
                </div>
            </div>
        }
    </div>
</div>

src/MsCoreOne.FrontMvc/Views/Product/Index.cshtml
@model MsCoreOne.FrontMvc.Models.ProductVm
@{
    ViewData["Title"] = "Product detail";
}
    <div class="container">
        <div class="card card-product-detail">
            <div class="container-fliud">
                <div class="wrapper row">
                    <div class="preview col-md-6">
                        <div class="preview-pic tab-content">
                            <div class="tab-pane active" id="pic-1"><img src="@ViewData["BackendUrl"]@Model.ThumbnailImageUrl" /></div>
                            <div class="tab-pane" id="pic-2"><img src="@ViewData["BackendUrl"]@Model.ThumbnailImageUrl" /></div>
                            <div class="tab-pane" id="pic-3"><img src="@ViewData["BackendUrl"]@Model.ThumbnailImageUrl" /></div>
                        </div>
                        <ul class="preview-thumbnail nav nav-tabs">
                            <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="@ViewData["BackendUrl"]@Model.ThumbnailImageUrl" /></a></li>
                            <li><a data-target="#pic-2" data-toggle="tab"><img src="@ViewData["BackendUrl"]@Model.ThumbnailImageUrl" /></a></li>
                            <li><a data-target="#pic-3" data-toggle="tab"><img src="@ViewData["BackendUrl"]@Model.ThumbnailImageUrl" /></a></li>
                        </ul>

                    </div>
                    <div class="details col-md-6">
                        <h3 class="product-title">@Model.Name</h3>
                        <div class="rating">
                            <vc:star rating="@Model.Rating"></vc:star>
                        </div>
                        <p class="product-description">@Model.Description</p>
                        <h4 class="price">current price: <span>$@Model.Price</span></h4>
                        <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
                        <h5 class="sizes">
                            sizes:
                            <span class="size" data-toggle="tooltip" title="small">s</span>
                            <span class="size" data-toggle="tooltip" title="medium">m</span>
                            <span class="size" data-toggle="tooltip" title="large">l</span>
                            <span class="size" data-toggle="tooltip" title="xtra large">xl</span>
                        </h5>
                        <h5 class="colors">
                            colors:
                            <span class="color orange not-available" data-toggle="tooltip" title="Not In store"></span>
                            <span class="color green"></span>
                            <span class="color blue"></span>
                        </h5>
                        <div class="action">
                            <button class="add-to-cart btn btn-default" type="button">add to cart</button>
                            <button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

src/MsCoreOne.FrontMvc/Views/Shared/Components/Categories/Default.cshtml
@model IEnumerable<MsCoreOne.FrontMvc.Models.CategoryVm>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item" asp-controller="Home" asp-action="Index">All</a>
        @foreach (var category in Model)
        {
            <a class="dropdown-item" id="@category.Id" asp-controller="Home" asp-action="Index" asp-route-categoryId="@category.Id">@category.Name</a>
        }
    </div>
</li>
        

src/MsCoreOne.FrontMvc/Views/Shared/Components/Star/Default.cshtml
@model int

<div>
    @for (int i = 0; i < 5; i++)
    {
        if (i < Model)
        {
            <svg style="color:#ffbf00" class="bi bi-star-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
            </svg>
        }
        else
        {
            <svg class="bi bi-star" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z" />
            </svg>
        }
    }
</div>

src/MsCoreOne.FrontMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MsCoreOne.FrontMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MsCoreOne.FrontOffice</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <vc:categories></vc:categories>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MsCoreOne.FrontMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>